 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.1 Build 231207
//-----------------------------------------------------------------------------
#include "ht32.h"
#include "GPIO.h"
#include "SysTick.h"
#include "BFTM0.h"
#include "ADC.h"
#include "UART1.h"
#include "USART1.h"
#include "I2C0.h"
#include "I2C1.h"
#include "MCTM0.h"
#include "Emulate_EEPROM.h"


//-----------------------------------------------------------------------------
int main(void)
{
  GPIO_Configuration();
  SysTick_Configuration();
  BFTM0_Configuration();
  ADC_Configuration();
  UART1_Configuration();
  USART1_Configuration();
  I2C0_Configuration();
  I2C1_Configuration();
  MCTM0_Configuration();
  Emulate_EEPROM_Configuration();

  while (1)
  {
    if(HT_CKCU->APBCCR1 & (1 << 4))
      WDT_Restart();
    //USART1_test(); //Can be removed
    //I2C0_test();   //Can be removed
    //I2C1_test();   //Can be removed
    //Emulate_EEPROM_test();  //Can be removed

  }
}
