 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.1 Build 231207

#include "middleware\eeprom_emulation.h"
#include "ht32_eeprom_config.h"

/* Dependency check ----------------------------------------------------------------------------------------*/
#if (__CORTEX_M == 0)
#define MIN_HT32_FWLIB_VER              (0x01000025) //0xmmnnnrrr -> Vm.n.r
#define MIN_HT32_FWLIB_SVN              (0x5816)
#endif
#if (__CORTEX_M == 3)
#define MIN_HT32_FWLIB_VER              (0x01000010) //0xmmnnnrrr -> Vm.n.r
#define MIN_HT32_FWLIB_SVN              (0x2581)
#endif
#include "ht32_dependency.h" // Not exist means the version of HT32 Firmware Library is older than the module required.


/* Private variables ---------------------------------------------------------------------------------------*/
u16 EEPROM_VarAddrTab[EEPROM_EMU_LENGTH];

/* Private function prototypes -----------------------------------------------------------------------------*/

//-----------------------------------------------------------------------------
void Emulate_EEPROM_Configuration(void)
{
  u16 i;
  
  for(i=0; i<EEPROM_EMU_LENGTH; i++) //MUST initial the index at least once
  {
    EEPROM_VarAddrTab[i] = 0x5A00 + i;
  }
  EEPROM_Init();
}


//-----------------------------------------------------------------------------
void Emulate_EEPROM_test(void)
{
  EEPROM_EMU_State EepromStatus;
  u16 i, data[EEPROM_EMU_LENGTH];
  

  for(i=0; i<EEPROM_EMU_LENGTH; i++)
  {
    EepromStatus = EEPROM_Read(EEPROM_VarAddrTab[i], &data[i]);     //read example
    if (EepromStatus != EEPROM_EMU_OPERATION_OK)
    {
      data[i] = 0;  //default value for the first time write
      //...add your code
    }
    
    EepromStatus = EEPROM_Write(EEPROM_VarAddrTab[i], data[i] + 1); //write example
    if (EepromStatus != EEPROM_EMU_OPERATION_OK)
    {
      //...add your code
    }
  }
}




