 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.1 Build 231207
//-----------------------------------------------------------------------------
#ifndef __GPIO_H
#define __GPIO_H

#include "ht32.h"

//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------
#define OUT_PA2_PORT           A
#define OUT_PA2_PIN            2
#define OUT_PA2_GPIO_CLK      STRCAT2(P,          OUT_PA2_PORT)
#define OUT_PA2_GPIO_ID       STRCAT2(GPIO_P,     OUT_PA2_PORT)
#define OUT_PA2_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PA2_PORT)
#define OUT_PA2_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PA2_PIN)
#define OUT_PA2_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PA2_HIGH          OUT_PA2_GPIO_PORT->SRR    = OUT_PA2_GPIO_PIN
#define OUT_PA2_LOW           OUT_PA2_GPIO_PORT->RR     = OUT_PA2_GPIO_PIN
#define OUT_PA2_XOR           OUT_PA2_GPIO_PORT->DOUTR ^= OUT_PA2_GPIO_PIN

#define OUT_PA3_PORT           A
#define OUT_PA3_PIN            3
#define OUT_PA3_GPIO_CLK      STRCAT2(P,          OUT_PA3_PORT)
#define OUT_PA3_GPIO_ID       STRCAT2(GPIO_P,     OUT_PA3_PORT)
#define OUT_PA3_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PA3_PORT)
#define OUT_PA3_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PA3_PIN)
#define OUT_PA3_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PA3_HIGH          OUT_PA3_GPIO_PORT->SRR    = OUT_PA3_GPIO_PIN
#define OUT_PA3_LOW           OUT_PA3_GPIO_PORT->RR     = OUT_PA3_GPIO_PIN
#define OUT_PA3_XOR           OUT_PA3_GPIO_PORT->DOUTR ^= OUT_PA3_GPIO_PIN

#define OUT_PC4_PORT           C
#define OUT_PC4_PIN            4
#define OUT_PC4_GPIO_CLK      STRCAT2(P,          OUT_PC4_PORT)
#define OUT_PC4_GPIO_ID       STRCAT2(GPIO_P,     OUT_PC4_PORT)
#define OUT_PC4_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PC4_PORT)
#define OUT_PC4_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PC4_PIN)
#define OUT_PC4_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PC4_HIGH          OUT_PC4_GPIO_PORT->SRR    = OUT_PC4_GPIO_PIN
#define OUT_PC4_LOW           OUT_PC4_GPIO_PORT->RR     = OUT_PC4_GPIO_PIN
#define OUT_PC4_XOR           OUT_PC4_GPIO_PORT->DOUTR ^= OUT_PC4_GPIO_PIN



//-----------------------------------------------------------------------------
void GPIO_Configuration(void);

#endif

