 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.1 Build 231207
//-----------------------------------------------------------------------------
#include "MCTM0.h"

//-----------------------------------------------------------------------------
#define MCTM0_TIMER_BASE            ((long long)SystemCoreClock / 1000)

//-----------------------------------------------------------------------------
void MCTM0_Configuration(void)
{
  u32 wCRR = 0, wPSCR = 0;
  TM_TimeBaseInitTypeDef TM_TimeBaseInitStruct;
  TM_OutputInitTypeDef TM_OutputInitStruct;
  CKCU_PeripClockConfig_TypeDef CKCUClock = {{ 0 }};
  CKCUClock.Bit.MCTM0      = 1;
  CKCUClock.Bit.AFIO       = 1;
  CKCU_PeripClockConfig(CKCUClock, ENABLE);

  AFIO_GPxConfig(GPIO_PA, AFIO_PIN_14, AFIO_FUN_MCTM_GPTM);  //Config AFIO mode
  AFIO_GPxConfig(GPIO_PB, AFIO_PIN_0, AFIO_FUN_MCTM_GPTM);  //Config AFIO mode
  AFIO_GPxConfig(GPIO_PD, AFIO_PIN_1, AFIO_FUN_MCTM_GPTM);  //Config AFIO mode
  wCRR = MCTM0_TIMER_BASE - 1;
  while ((wCRR / (wPSCR + 1)) > 0xFFFF)
  {
    wPSCR++;
  }
  wCRR = wCRR / (wPSCR + 1);

  TM_TimeBaseInitStruct.CounterReload = wCRR;
  TM_TimeBaseInitStruct.Prescaler = wPSCR;
  TM_TimeBaseInitStruct.RepetitionCounter = 0;
  TM_TimeBaseInitStruct.CounterMode = TM_CNT_MODE_UP;
  TM_TimeBaseInitStruct.PSCReloadTime = TM_PSC_RLD_IMMEDIATE;
  TM_TimeBaseInit(HT_MCTM0, &TM_TimeBaseInitStruct);

  TM_OutputInitStruct.Channel = TM_CH_0;
  TM_OutputInitStruct.OutputMode = TM_OM_PWM2;
  TM_OutputInitStruct.Control = TM_CHCTL_ENABLE;
  TM_OutputInitStruct.ControlN = TM_CHCTL_ENABLE;
  TM_OutputInitStruct.Polarity = TM_CHP_NONINVERTED;
  TM_OutputInitStruct.PolarityN = TM_CHP_NONINVERTED;
  TM_OutputInitStruct.IdleState = MCTM_OIS_LOW;
  TM_OutputInitStruct.IdleStateN = MCTM_OIS_HIGH;
  TM_OutputInitStruct.Compare = ((wCRR + 1) * (100 - 50)) / 100;
  TM_OutputInit(HT_MCTM0, &TM_OutputInitStruct);

  TM_OutputInitStruct.Channel = TM_CH_1;
  TM_OutputInitStruct.OutputMode = TM_OM_PWM2;
  TM_OutputInitStruct.Control = TM_CHCTL_ENABLE;
  TM_OutputInitStruct.ControlN = TM_CHCTL_ENABLE;
  TM_OutputInitStruct.Polarity = TM_CHP_NONINVERTED;
  TM_OutputInitStruct.PolarityN = TM_CHP_NONINVERTED;
  TM_OutputInitStruct.IdleState = MCTM_OIS_LOW;
  TM_OutputInitStruct.IdleStateN = MCTM_OIS_HIGH;
  TM_OutputInitStruct.Compare = ((wCRR + 1) * (100 - 50)) / 100;
  TM_OutputInit(HT_MCTM0, &TM_OutputInitStruct);

  TM_OutputInitStruct.Channel = TM_CH_2;
  TM_OutputInitStruct.OutputMode = TM_OM_PWM2;
  TM_OutputInitStruct.Control = TM_CHCTL_ENABLE;
  TM_OutputInitStruct.ControlN = TM_CHCTL_ENABLE;
  TM_OutputInitStruct.Polarity = TM_CHP_NONINVERTED;
  TM_OutputInitStruct.PolarityN = TM_CHP_NONINVERTED;
  TM_OutputInitStruct.IdleState = MCTM_OIS_LOW;
  TM_OutputInitStruct.IdleStateN = MCTM_OIS_HIGH;
  TM_OutputInitStruct.Compare = ((wCRR + 1) * (100 - 50)) / 100;
  TM_OutputInit(HT_MCTM0, &TM_OutputInitStruct);

  MCTM_CHMOECmd(HT_MCTM0, ENABLE);
  TM_Cmd(HT_MCTM0, ENABLE);
}

//-----------------------------------------------------------------------------
void MCTM0_SetFrequency(u32 freq)
{
  TM_TimeBaseInitTypeDef TM_TimeBaseInitStruct;
  uint32_t wCRR = 0, wPSCR = 0;

  wCRR = (SystemCoreClock / freq) - 1;
  while ((wCRR / (wPSCR + 1)) > 0xFFFF)
  {
    wPSCR++;
  }
  wCRR = wCRR / (wPSCR + 1);

  TM_TimeBaseInitStruct.CounterReload = wCRR;
  TM_TimeBaseInitStruct.Prescaler = wPSCR;
  TM_TimeBaseInitStruct.RepetitionCounter = 0;
  TM_TimeBaseInitStruct.CounterMode = TM_CNT_MODE_UP;
  TM_TimeBaseInitStruct.PSCReloadTime = TM_PSC_RLD_IMMEDIATE;
  TM_TimeBaseInit(HT_MCTM0, &TM_TimeBaseInitStruct);

  TM_SetCaptureCompare0(HT_MCTM0, 0); //set on duty to 0
  TM_SetCaptureCompare1(HT_MCTM0, 0); //set on duty to 0
  TM_SetCaptureCompare2(HT_MCTM0, 0); //set on duty to 0
}

//-----------------------------------------------------------------------------
void MCTM0_CH0_SetOnduty(u8 percent)
{
  u16 cmp;
  cmp = HT_MCTM0->CRR * (255-percent) / 255;
  TM_SetCaptureCompare0(HT_MCTM0, cmp);
}

//-----------------------------------------------------------------------------
void MCTM0_CH0_EnablePWMOutput(void)
{
  AFIO_GPxConfig(GPIO_PA, AFIO_PIN_14, AFIO_FUN_MCTM_GPTM);  //Config AFIO mode
}

//-----------------------------------------------------------------------------
void MCTM0_CH0_DisablePWMOutput(u8 IO_State)
{
  CKCU_PeripClockConfig_TypeDef CKCUClock = {{ 0 }};
  CKCUClock.Bit.AFIO       = 1;
  CKCUClock.Bit.PA         = 1;
  CKCU_PeripClockConfig(CKCUClock, ENABLE);

  if(IO_State)
    GPIO_SetOutBits  (HT_GPIOA, AFIO_PIN_14);
  else
    GPIO_ClearOutBits(HT_GPIOA, AFIO_PIN_14);
  GPIO_DirectionConfig(HT_GPIOA, AFIO_PIN_14, GPIO_DIR_OUT);
  AFIO_GPxConfig(GPIO_PA, AFIO_PIN_14, AFIO_FUN_GPIO);  //Config AFIO mode
}


//-----------------------------------------------------------------------------
void MCTM0_CH1_SetOnduty(u8 percent)
{
  u16 cmp;
  cmp = HT_MCTM0->CRR * (255-percent) / 255;
  TM_SetCaptureCompare1(HT_MCTM0, cmp);
}

//-----------------------------------------------------------------------------
void MCTM0_CH1_EnablePWMOutput(void)
{
  AFIO_GPxConfig(GPIO_PB, AFIO_PIN_0, AFIO_FUN_MCTM_GPTM);  //Config AFIO mode
}

//-----------------------------------------------------------------------------
void MCTM0_CH1_DisablePWMOutput(u8 IO_State)
{
  CKCU_PeripClockConfig_TypeDef CKCUClock = {{ 0 }};
  CKCUClock.Bit.AFIO       = 1;
  CKCUClock.Bit.PB         = 1;
  CKCU_PeripClockConfig(CKCUClock, ENABLE);

  if(IO_State)
    GPIO_SetOutBits  (HT_GPIOB, AFIO_PIN_0);
  else
    GPIO_ClearOutBits(HT_GPIOB, AFIO_PIN_0);
  GPIO_DirectionConfig(HT_GPIOB, AFIO_PIN_0, GPIO_DIR_OUT);
  AFIO_GPxConfig(GPIO_PB, AFIO_PIN_0, AFIO_FUN_GPIO);  //Config AFIO mode
}


//-----------------------------------------------------------------------------
void MCTM0_CH2_SetOnduty(u8 percent)
{
  u16 cmp;
  cmp = HT_MCTM0->CRR * (255-percent) / 255;
  TM_SetCaptureCompare2(HT_MCTM0, cmp);
}

//-----------------------------------------------------------------------------
void MCTM0_CH2_EnablePWMOutput(void)
{
  AFIO_GPxConfig(GPIO_PD, AFIO_PIN_1, AFIO_FUN_MCTM_GPTM);  //Config AFIO mode
}

//-----------------------------------------------------------------------------
void MCTM0_CH2_DisablePWMOutput(u8 IO_State)
{
  CKCU_PeripClockConfig_TypeDef CKCUClock = {{ 0 }};
  CKCUClock.Bit.AFIO       = 1;
  CKCUClock.Bit.PD         = 1;
  CKCU_PeripClockConfig(CKCUClock, ENABLE);

  if(IO_State)
    GPIO_SetOutBits  (HT_GPIOD, AFIO_PIN_1);
  else
    GPIO_ClearOutBits(HT_GPIOD, AFIO_PIN_1);
  GPIO_DirectionConfig(HT_GPIOD, AFIO_PIN_1, GPIO_DIR_OUT);
  AFIO_GPxConfig(GPIO_PD, AFIO_PIN_1, AFIO_FUN_GPIO);  //Config AFIO mode
}


//-----------------------------------------------------------------------------


