 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.1 Build 231207
//-----------------------------------------------------------------------------
#ifndef __MCTM0_H
#define __MCTM0_H


//-----------------------------------------------------------------------------
#include "ht32.h"

//-----------------------------------------------------------------------------
void MCTM0_Configuration(void);
void MCTM0_SetFrequency(u32 freq);
void MCTM0_CH0_SetOnduty(u8 percent);
void MCTM0_CH0_EnablePWMOutput(void);
void MCTM0_CH0_DisablePWMOutput(u8 IO_State);
void MCTM0_CH1_SetOnduty(u8 percent);
void MCTM0_CH1_EnablePWMOutput(void);
void MCTM0_CH1_DisablePWMOutput(u8 IO_State);
void MCTM0_CH2_SetOnduty(u8 percent);
void MCTM0_CH2_EnablePWMOutput(void);
void MCTM0_CH2_DisablePWMOutput(u8 IO_State);

//-----------------------------------------------------------------------------
#endif

